name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.svg
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, achievements
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          token: ${{ secrets.METRICS_TOKEN }}
