name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/github_info.svg
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, plugin_languages
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_limit: 4
          plugin_languages_other: yes
          plugin_languages_details: bytes-size, percentage
          token: ${{ secrets.METRICS_TOKEN }}

      - uses: lowlighter/metrics@latest
        with:
          filename: assets/steam_info.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198244222758"
          plugin_steam_games_ignored: "431960"